apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: greetings-app
  template:
    metadata:
      labels:
        app: greetings-app
    spec:
      nodeSelector:
        app: greetings-app
      containers:
      - name: greetings-app
        image: shivaaksacr.azurecr.io/greetings-app:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shiva-configmap
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: shiva-secret